apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: haproxy
  namespace: graphtuitous
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: graphtuitous
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: haproxy
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: haproxy-
      labels:
        build.appstudio.openshift.io/application: graphtuitous
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: haproxy
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: graphtuitous
    spec:
      params:
      - name: git-url
        value: https://github.com/jduimovich/graphtuitous
      - name: output-image
        value: quay.io/jduimovich0/haproxy:latest-$(tt.params.git-revision)
      - name: dockerfile
        value: services/haproxy/Dockerfile
      - name: path-context
        value: services/haproxy
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:3dddea8074c9fa13e7146e3c5c7d75e4bd8f7bb0
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: haproxy/$(tt.params.git-revision)
      - name: registry-auth
        secret:
          secretName: redhat-appstudio-registry-pull-secret
    status: {}
status: {}
